name: Build glfw-skeleton

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libglu1-mesa-dev
    - name: make
      run: make
